export const SET_TODOS = 'todos/SET_TODOS'
export const ADD_TODO_START = 'todos/ADD_TODO_START'
export const ADD_TODO_SUCCESS = 'todos/ADD_TODO_SUCCESS'
export const TOGGLE_TODO = 'todos/TOGGLE_TODO'
export const REMOVE_TODO = 'todos/REMOVE_TODO'
export const FETCH_TODOS = 'todos/FETCH_TODOS'
