export const SET_TODOS = 'todos/SET_TODOS'
export const ADD_TODO = 'todos/ADD_TODO'
export const TOGGLE_TODO = 'todos/TOGGLE_TODO'
export const REMOVE_TODO = 'todos/REMOVE_TODO'
export const FETCH_TODOS = 'todos/FETCH_TODOS'
